name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: docker/setup-compose-action@v1.2.0
    - name: Mount Dockerfile
      run: docker compose -f ../__test/docker-compose.yml up --detach;
      
    - name: Run Dockerfile
      run: docker exec -it criterion_minishell_rpassos_videsou make re -C __test
